const meals = [
	{name: "Pates", weight: 1, max: 1},
	{name: "Cordon Bleu", weight: 0.5, max: 1},
	{name: "Carrotes", weight: 1, max: 3},
	{name: "Riz-Chili", weight: 0.8, max: 1},
	{name: "Ramen", weight: 0.2, max:1},
	{name: "Saumon fumé", weight: 0.1, max:1},
	{name: "Steak + Broccoli", weight:0.3, max:1},
	{name: "Galette bretonnes", weight:0.3, max:1},
	{name: "Hamburger", weight:0.2, max:1},
	{name: "Lentilles", weight:0.3, max:1},
	{name: "Beans", weight:0.3, max:1},
	{name: "Pois-Chiches", weight:0.6, max:1},
	{name: "Riz-Poulet", weight:0.3, max:1},
	{name: "Jambon à poeler", weight:0.2, max:1},
	{name: "Tortelini", weight:0.4, max:1},
	{name: "Gnocchi", weight:0.2, max:1},
	{name: "Spaetzle", weight:0.2, max:1},
	{name: "Escalopes Panées", weight:0.3, max:1},
	{name: "Ravioli", weight:0.3, max:1},
	{name: "Croque-Monsieur", weight:0.2, max:1},
	{name: "Canard", weight:0.05, max:1},
	{name: "Purée", weight:0.1, max:1},
	{name: "Cereales Tex-Mex", weight:0.4, max:1},
	{name: "Oeufs", weight:0.5, max:1},
	{name: "Poulet à rechauffer", weight:0.2, max:1}
	//{name: "", weight:, max:},
	];
