const groups = [
	{group: "Pate", max:1},
	{group: "Viande", max:2},
	{group: "Feculent", max:2},
]

const meals = [
	{name: "Pates-Pesto", group:"Pate", weight: 1, max: 1},
	{name: "Pates-Bolo", group:"Pate", weight: 1, max: 1},
	{name: "Pates-Creme", group:"Pate", weight: 1, max: 1},
	{name: "Cordon Bleu", group:"Viande", weight: 0.5, max: 1},
	{name: "Carrotes", weight: 1, max: 3},
	{name: "Riz-Chili", group:"Feculent", weight: 0.8, max: 1},
	{name: "Ramen", group: "Feculent", weight: 0.2, max:1},
	{name: "Saumon fumé",group:"Viande", weight: 0.1, max:1},
	{name: "Steak + Broccoli",group:"Viande", weight:0.3, max:1},
	{name: "Galette bretonnes",group:"Viande", weight:0.3, max:1},
	{name: "Hamburger",group:"Viande", weight:0.2, max:1},
	{name: "Lentilles", weight:0.3, max:1},
	{name: "Beans", weight:0.3, max:1},
	{name: "Pois-Chiches", weight:0.6, max:1},
	{name: "Riz-Poulet", weight:0.3, max:1},
	{name: "Jambon à poeler",group:"Viande", weight:0.2, max:1},
	{name: "Tortelini",group:"Feculent", weight:0.4, max:1},
	{name: "Gnocchi",group:"Feculent", weight:0.2, max:1},
	{name: "Spaetzle", group:"Feculent", weight:0.2, max:1},
	{name: "Escalopes Panées",group:"Viande", weight:0.3, max:1},
	{name: "Ravioli", group:"Feculent", weight:0.3, max:1},
	{name: "Croque-Monsieur",group:"Viande", weight:0.2, max:1},
	{name: "Canard",group:"Viande", weight:0.05, max:1},
	{name: "Purée", weight:0.1, max:1},
	{name: "Cereales Tex-Mex", group:"Feculent", weight:0.4, max:1},
	{name: "Oeufs", weight:0.5, max:1},
	{name: "Poulet à rechauffer",group:"Viande", weight:0.2, max:1}
	//{name: "", weight:, max:},
	];
